### ISSUE TITLE
Copy/paste song line does not work

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#25]
Could you please check if song line copy/paste works?

I was not able to do it. Nothing is pasted.

**Comment by GSoftwareDevelopment** [comment]
The thing with copy/paste operations is that once the operation is done, no changes can be made.
This is because the clipboard operation uses an area of memory that is modified when you make a change to the TAB.
Hence, loss of clipboard data may occur.

So far, I will not solve this problem as there is not much space in memory for an independent clipboard. Hence sharing with other operations.

**Comment by tatqoo** [comment]
I am not sure if you understood. I am able to copy instruments and tabs, but I was not able to copy song lines at all. I understood that you said copying song lines is also possible, so I tried and no success.

**Comment by tatqoo** [comment]
Like Control+C/Control+V does not work for song lines. Has it been implemented for song lines?

**Comment by GSoftwareDevelopment** [comment]
Clipboard operations for the SONG module are not implemented.

This is because I would have to create the ability to select individual lines (blocks), and this builds code for which there is not much space in memory.

So the clipboard operations in SFX and TAB modules are ONLY on whole definitions.

**Comment by tatqoo** [comment]
Thanks. That means I misunderstood you.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
