### ISSUE TITLE
Keyboard play on the current channel during song replay

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#4]
Keyboard play on the current channel during the song play

**Comment by GSoftwareDevelopment** [comment]
Finally done.

It works a little strangely.
**CONTROL+Left/Right** arrows select channel
**Left/right** arrows - select SFX

I forgot about fast keys for SFX :/ - that's why I don't close the application.

Playback on the selected channel is interrupted when the piano is used, but will resume when a TAB is defined on that channel when you go to the next SONG line.

**Comment by tatqoo** [comment]
Works fine. This request has been closed.
