### ISSUE TITLE
Number of steps during TAB edit should be definable

### ISSUE THREAD

**Issue by tatqoo** [GSoftwareDevelopment/SFX-Tracker#9]
Number of steps during TAB edit should be definable.

Currently after pressing a key it goes to the next line. It should be possible to define how many steps should be skipped.

This will enable playing / capturing arpegios/bass lines easier.

**Comment by GSoftwareDevelopment** [comment]
OK, it only records here what was agreed upon at the meeting.

The numeric keys 1 through 8 will be used to select the step, along with the `CONTROL` key, that is:
- CONTROL+1 will set a step every one line
- CONTROL+2 sets a step every two lines
- CONTROL+3 sets a step every three lines
- and so on.

**Comment by tatqoo** [comment]
Thanks!

I am a bit afraid of how useful it will be for higher tempos 01//02. Would
that be possible in the future to add also the step multiplier (1 or two or
three or four)? I will tell more once I try the higher tempos.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by GSoftwareDevelopment** [comment]
I was mad when I came up with this (or vice versa)

A solution has been implemented that allows you to set the step of moving the cursor in TAB edit mode.

The CONTROL keys and the digits 0 through 9 are used for this function.

Working principle.
Selecting 0 sets the step value to 0. However, selecting numbers 1 through 9 increases the step value by the selected number.
As a result, selecting a step "every 1 line" is:
CONTROL+0 and CONTROL+1

Setting a step "every 4 lines" is (holding CONTROL) press the digits 0 and 4.
For a step of 12, there are more combinations, because the value 12 can be obtained by selecting the numbers: 0, 6, 6 or 0,5,5,2, or 0 and press 1 twelve times :D

The maximum step value is 32, above this value the step resets to zero.

As for me, mega :D

**Comment by GSoftwareDevelopment** [comment]
There is an idea to solve this request differently.
That is, use a single hotkey, such as CONTROL+S, and show a prompt telling you to enter a new step value.

**Comment by tatqoo** [comment]
I would leave Control+S for possible future saving shortcuts. Control+B for
Beat?

**Comment by GSoftwareDevelopment** [comment]
OK, this will be CONTROL+B
